### ISSUE TITLE
No metrics are coming after running the example task

### ISSUE THREAD

**Issue by PraveenkumarDonga** [intelsdi-x/snap-plugin-collector-mongodb#5]
Hi!
I have installed the mongodb plugin and downloaded the task and ran from sanp
using the command <snaptel task create -t  mongodb-file.yaml>
Task ID is created.
I am trying to see the metrics using the command {snaptel task watch <taks ID>}
but nothing is coming and there is no file created with name /tmp/mongodb_metrics
Could you please help me with this.

And one more thing I want to know is,  this plugin is just to see the metrics of the mongodb or even we can see the the date stored in the db. Basically we are planning to see the sensor data(real time data) which will be stored in mongodb. Is this plugin useful for that?

**Comment by sandlbn** [comment]
which version of mongodb are you using ? Right now mongodb 3.2.x and 3.4.x are supported. Also this file is named /tmp/mongodb_metrics.log 
1. did you get any error ? 
2. Can you post a log from snapteld ? with -d 1 parameter.  Something like snapteld -d 1 -t 0

**Comment by PraveenkumarDonga** [comment]
Hi!
I am using mongodb version 3.2.11.
Even I can't see the file /tmp/mongodb_metrics.log.
I didn't get any error while running the task for the first time (yesterday)
But today I am getting Errors while running the task.
and could you please tell me how to get the log from snapteld. 

Thanks,
Praveen.
![selection_004](https://cloud.githubusercontent.com/assets/8088246/20743216/1ca8f0c8-b6fb-11e6-966a-fab1db72a0de.png)

**Comment by PraveenkumarDonga** [comment]
Sorry My bad!
I didn't load the mongodb plugin before running the task.
now task is running but that mongodb_metrics.log file is not getting created.

**Comment by kindermoumoute** [comment]
> now task is running but that mongodb_metrics.log file is not getting created.

If I understand, you are using the task manifest given [in the example folder](https://github.com/intelsdi-x/snap-plugin-collector-mongodb/blob/master/examples/tasks/mongodb-file.yaml).

I think you are really close to make it. Assuming your mongodb is running and `config.json` matches with mongodb logs, here is a sum up of the different steps you did:
- start Snap daemon with the mongodb config `snapteld -t 0 --config examples/configs/config.json`.
- load plugins `snaptel plugin load snap-plugin-collector-mongodb && snaptel plugin load snap-plugin-publisher-file`.
- start the task (your screenshot).

At this moment you should be able to see the published metrics, e.g. `cat /tmp/mongodb_metrics.log`.

If this doesn't show anything, can you show the state of the task with `snaptel task list`?
@PraveenkumarDonga

**Comment by PraveenkumarDonga** [comment]
Hi!
I am starting the snap daemon with **<<systemctl start snap-telemetry>>** not as you mentioned .
Even I tried with the way you mentioned but that **config.json** file is missing.
I have seen these files only in that path(**/opt/snap/examples/configs**).
**snap-config-sample.json  
snap-config-sample.yaml  
snapctl-config-sample.json**

This is the screen shot of snaptel task list
![selection_005](https://cloud.githubusercontent.com/assets/8088246/20745862/2cec19e8-b709-11e6-98dd-a6673a320263.png)

**Comment by kindermoumoute** [comment]
@PraveenkumarDonga I was talking about [this config file](https://github.com/intelsdi-x/snap-plugin-collector-mongodb/blob/master/examples/configs/config.json).

More info about how to fill this config file [here](https://github.com/intelsdi-x/snap-plugin-collector-mongodb#global-config).

**Comment by sandlbn** [comment]
@PraveenkumarDonga  I will check for you know, and I will update in an hour.

**Comment by sandlbn** [comment]
@PraveenkumarDonga  ok indeed there where some issues with config example and task manifest please check PR #6 and download new task manifest. https://github.com/intelsdi-x/snap-plugin-collector-mongodb/pull/6  . You don't need to add configuration to your snapd config. Task manifest should be enough.

**Comment by sandlbn** [comment]
@PraveenkumarDonga  can you give us update on your issue ?

**Comment by mkleina** [comment]
Tested plugin right now, config works OK (both global and inside task).

By the way, I found another bug, I'll create Pull Request to fix it (tcmalloc not available by default in MongoDB 2.6.10)

**Comment by PraveenkumarDonga** [comment]
Hi! sandlbn, 
Just now I cloned it and built the plug-in using make.
Now it is working fine. Logs are coming. 

Thanks

**Comment by IzabellaRaulin** [comment]
@PraveenkumarDonga, I will close this issue based on your what you wrote above that now it is working fine. Do not do hesitate to open a new issue or re-open that one if you have any problem with mongodb collector. Thank You.
